version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@7.0.0
  aws-cli: circleci/aws-cli@2.0.0
  node: circleci/node@2.0.2

jobs:
  # Job to deploy the React app to EC2
  Deploy_React_App_On_EC2:
    docker:
      - image: cimg/node:18.0.0  # Using node 18 image for EC2 deployment
    steps:
      - run:
          name: SSH into EC2 and Deploy React App
          command: |
            ssh -i "Akshya-Keypair.pem" -o StrictHostKeyChecking=no ec2-user@ec2-52-17-173-250.eu-west-1.compute.amazonaws.com './Deploysshfile.sh'

  # Build and Push Docker Image to AWS ECR
  build_and_push_image:
    docker:
      - image: cimg/node:18.0.0  # Using node 18 image for Docker build
    steps:
      - checkout
      - setup_remote_docker:  # Enabling Docker in remote environment without specifying version
          docker_layer_caching: true  # Optional, speeds up builds by caching layers
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL_REACT
          aws-access-key-id: ACCESS_KEY_ID_REACT
          aws-secret-access-key: SECRET_ACCESS_KEY_REACT
          dockerfile: Env/Dockerfile
          path: .
          region: AWS_REGION_REACT
          repo: demo repo
          tag: latest,0.1$CIRCLE_BUILD_NUM

  # Manual approval job for deployment
  Deployment_React_Approval:
    type: approval
    requires:
      - build_and_push_image

workflows:
  version: 2
  build_and_push_image:
    jobs:
      - build_and_push_image:
          filters:
            branches:
              only: main
      - Deployment_React_Approval:
          requires:
            - build_and_push_image
          filters:
            branches:
              only: main
      - Deploy_React_App_On_EC2:
          requires:
            - Deployment_React_Approval
          filters:
            branches:
              only: main
