version: 2.1

# Using the latest versions of orbs for best compatibility
orbs:
  aws-ecr: circleci/aws-ecr@7.1.0
  aws-cli: circleci/aws-cli@2.0.1
  node: circleci/node@4.1.0

jobs:
  # Job to deploy the React app to EC2
  Deploy_React_App_On_EC2:
    machine:
      enabled: true
    steps:
      - run:
          name: SSH into EC2 and Deploy React App
          command: |
            ssh -i private_key.pem ec2-user@${EC2_PUBLIC_IP} './deploy.sh'

  # Build and Push Docker Image to AWS ECR
  build_and_push_image:
    docker:
      - image: circleci/python:3.9  # Or choose an image more relevant to your environment
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7  # Specify Docker version for remote Docker executor
          docker_layer_caching: true
      - run:
          name: Install dependencies
          command: |
            # Add commands for installing dependencies (e.g., node, npm)
            curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
            apt-get install -y nodejs
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL_REACT
          aws-access-key-id: AWS_ACCESS_KEY_ID_REACT
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY_REACT
          dockerfile: Env/DockerFile
          path: .
          region: AWS_REGION_REACT
          repo: devops-demo
          tag: latest,0.1${CIRCLE_BUILD_NUM}

  # Manual approval job for deployment
  Deployment_React_Approval:
    type: approval
    requires:
      - build_and_push_image

workflows:
  version: 2
  build_and_push_image:
    jobs:
      - build_and_push_image:
          filters:
            branches:
              only: main
      - Deployment_React_Approval:
          requires:
            - build_and_push_image
          filters:
            branches:
              only: main
      - Deploy_React_App_On_EC2:
          requires:
            - Deployment_React_Approval
          filters:
            branches:
              only: main


