version: 2.1     

orbs:
  aws-ecr: circleci/aws-ecr@7.0.0
  aws-cli: circleci/aws-cli@2.0.0
  node: circleci/node@2.0.2

jobs:
  Deploy_React_App_On_EC2:
    machine:
      enabled: true
    steps:
      - run: 
          name: SSH_Into_EC2
          command: ssh -i ec2-user@ec2-13-215-206-191.ap-southeast-1.compute.amazonaws.com './demo-react-ssh.sh';

workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:  # Corrected job name
          account-url: AWS_ECR_ACCOUNT_URL_REACT
          aws-access-key-id: ACCESS_KEY_ID_REACT
          aws-secret-access-key: SECRET_ACCESS_KEY_REACT
          dockerfile: Env/DockerFile
          path: .
          no-output-timeout: 20m
          region: AWS_REGION_REACT
          repo: devops-demo
          skip-when-tags-exist: false
          tag: latest,0.1$CIRCLE_BUILD_NUM
          filters:
            branches:
              only: main
          
      - Deployment_React_Approval:
          type: approval
          requires:
            - aws-ecr/build-and-push-image
          filters:
            branches: 
              only: main

      - Deploy_React_App_On_EC2:
          requires:
            - Deployment_React_Approval
          filters:
            branches:
              only: main
